/* tslint:disable */
/* eslint-disable */
/**
 * Mission Management
 * ## PSID API Reference: PSID002 - Mission Management  The Mission API enables customers to create, update and delete missions. A mission is composed of one or more teams, their areas of operation and communication needs. The data can be used to issue an inquiry for matching products (see PSID001).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Another Characteristic that is related to the current Characteristic;
 * @export
 * @interface CharacteristicRelationship
 */
export interface CharacteristicRelationship {
    /**
     * Unique identifier of the characteristic
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    id?: string;
    /**
     * Hyperlink reference
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    href?: string;
    /**
     * The type of relationship
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    relationshipType?: string;
    /**
     * When sub-classing, this defines the super-class
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class Extensible name
     * @type {string}
     * @memberof CharacteristicRelationship
     */
    type?: string;
}

/**
 * Check if a given object implements the CharacteristicRelationship interface.
 */
export function instanceOfCharacteristicRelationship(
    value: object
): value is CharacteristicRelationship {
    return true;
}

export function CharacteristicRelationshipFromJSON(json: any): CharacteristicRelationship {
    return CharacteristicRelationshipFromJSONTyped(json, false);
}

export function CharacteristicRelationshipFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CharacteristicRelationship {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        href: json["href"] == null ? undefined : json["href"],
        relationshipType: json["relationshipType"] == null ? undefined : json["relationshipType"],
        baseType: json["@baseType"] == null ? undefined : json["@baseType"],
        schemaLocation: json["@schemaLocation"] == null ? undefined : json["@schemaLocation"],
        type: json["@type"] == null ? undefined : json["@type"]
    };
}

export function CharacteristicRelationshipToJSON(json: any): CharacteristicRelationship {
    return CharacteristicRelationshipToJSONTyped(json, false);
}

export function CharacteristicRelationshipToJSONTyped(
    value?: CharacteristicRelationship | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        href: value["href"],
        relationshipType: value["relationshipType"],
        "@baseType": value["baseType"],
        "@schemaLocation": value["schemaLocation"],
        "@type": value["type"]
    };
}
