/* tslint:disable */
/* eslint-disable */
/**
 * Mission Management
 * ## PSID API Reference: PSID002 - Mission Management  The Mission API enables customers to create, update and delete missions. A mission is composed of one or more teams, their areas of operation and communication needs. The data can be used to issue an inquiry for matching products (see PSID001).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * A GeoJSON MultiPoint.
 * @export
 * @interface MultiPoint
 */
export interface MultiPoint {
    /**
     *
     * @type {string}
     * @memberof MultiPoint
     */
    type?: string;
    /**
     *
     * @type {Array<Array<number>>}
     * @memberof MultiPoint
     */
    coordinates?: Array<Array<number>>;
}

/**
 * Check if a given object implements the MultiPoint interface.
 */
export function instanceOfMultiPoint(value: object): value is MultiPoint {
    return true;
}

export function MultiPointFromJSON(json: any): MultiPoint {
    return MultiPointFromJSONTyped(json, false);
}

export function MultiPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPoint {
    if (json == null) {
        return json;
    }
    return {
        type: json["type"] == null ? undefined : json["type"],
        coordinates: json["coordinates"] == null ? undefined : json["coordinates"]
    };
}

export function MultiPointToJSON(json: any): MultiPoint {
    return MultiPointToJSONTyped(json, false);
}

export function MultiPointToJSONTyped(
    value?: MultiPoint | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        type: value["type"],
        coordinates: value["coordinates"]
    };
}
