/* tslint:disable */
/* eslint-disable */
/**
 * Mission Management
 * ## PSID API Reference: PSID002 - Mission Management  The Mission API enables customers to create, update and delete missions. A mission is composed of one or more teams, their areas of operation and communication needs. The data can be used to issue an inquiry for matching products (see PSID001).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * An amount in a given unit
 * @export
 * @interface Quantity
 */
export interface Quantity {
    /**
     * Numeric value in a given unit
     * @type {number}
     * @memberof Quantity
     */
    amount?: number;
    /**
     * Unit
     * @type {string}
     * @memberof Quantity
     */
    units?: string;
}

/**
 * Check if a given object implements the Quantity interface.
 */
export function instanceOfQuantity(value: object): value is Quantity {
    return true;
}

export function QuantityFromJSON(json: any): Quantity {
    return QuantityFromJSONTyped(json, false);
}

export function QuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quantity {
    if (json == null) {
        return json;
    }
    return {
        amount: json["amount"] == null ? undefined : json["amount"],
        units: json["units"] == null ? undefined : json["units"]
    };
}

export function QuantityToJSON(json: any): Quantity {
    return QuantityToJSONTyped(json, false);
}

export function QuantityToJSONTyped(
    value?: Quantity | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        amount: value["amount"],
        units: value["units"]
    };
}
