/* tslint:disable */
/* eslint-disable */
/**
 * Mission Management
 * ## PSID API Reference: PSID002 - Mission Management  The Mission API enables customers to create, update and delete missions. A mission is composed of one or more teams, their areas of operation and communication needs. The data can be used to issue an inquiry for matching products (see PSID001).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Related Party reference. A related party defines party or party role linked to a specific entity.
 * @export
 * @interface RelatedParty
 */
export interface RelatedParty {
    /**
     * unique identifier
     * @type {string}
     * @memberof RelatedParty
     */
    id: string;
    /**
     * Hyperlink reference
     * @type {string}
     * @memberof RelatedParty
     */
    href?: string;
    /**
     * Name of the related entity.
     * @type {string}
     * @memberof RelatedParty
     */
    name?: string;
    /**
     * Role played by the related party
     * @type {string}
     * @memberof RelatedParty
     */
    role?: string;
    /**
     * When sub-classing, this defines the super-class
     * @type {string}
     * @memberof RelatedParty
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     * @type {string}
     * @memberof RelatedParty
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class Extensible name
     * @type {string}
     * @memberof RelatedParty
     */
    type?: string;
    /**
     * The actual type of the target instance when needed for disambiguation.
     * @type {string}
     * @memberof RelatedParty
     */
    referredType: string;
}

/**
 * Check if a given object implements the RelatedParty interface.
 */
export function instanceOfRelatedParty(value: object): value is RelatedParty {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("referredType" in value) || value["referredType"] === undefined) return false;
    return true;
}

export function RelatedPartyFromJSON(json: any): RelatedParty {
    return RelatedPartyFromJSONTyped(json, false);
}

export function RelatedPartyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedParty {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"],
        href: json["href"] == null ? undefined : json["href"],
        name: json["name"] == null ? undefined : json["name"],
        role: json["role"] == null ? undefined : json["role"],
        baseType: json["@baseType"] == null ? undefined : json["@baseType"],
        schemaLocation: json["@schemaLocation"] == null ? undefined : json["@schemaLocation"],
        type: json["@type"] == null ? undefined : json["@type"],
        referredType: json["@referredType"]
    };
}

export function RelatedPartyToJSON(json: any): RelatedParty {
    return RelatedPartyToJSONTyped(json, false);
}

export function RelatedPartyToJSONTyped(
    value?: RelatedParty | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        href: value["href"],
        name: value["name"],
        role: value["role"],
        "@baseType": value["baseType"],
        "@schemaLocation": value["schemaLocation"],
        "@type": value["type"],
        "@referredType": value["referredType"]
    };
}
