apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mission-management.fullname" . }}-config
  labels:
    {{- include "mission-management.labels" . | nindent 4 }}
data:
  config.yml: |
    database:
      scheme: "mongodb"
      host: {{ required "database.host is required" .Values.database.host | quote}}
      port: {{ .Values.database.port | quote }}
      user: {{ required "database.user is required" .Values.database.user | quote }}
      name: {{ .Values.database.name | quote }}
      authSource: {{ .Values.database.authSource | quote }}

    app:
      port: "7000"
      name: "PSI-MissionApi"
      timeout: 30
      demoData: true
      openApi:
        validation: false
        definition: ""

    logging:
      level: {{ .Values.logging.level | quote }}
      handler: {{ .Values.logging.handler | quote }}
