apiVersion: v1
kind: Service
metadata:
  name: {{ include "mission-management.fullname" . }}
  labels:
    {{- include "mission-management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mission-management.selectorLabels" . | nindent 4 }}
