version: '3.8'
services:
  web:
    image: 'docker.io/library/mongo-express'
    container_name: mongo-web
    restart: always
    ports:
      - '8888:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-db
    depends_on: db
    links:
      - db
  db:
    image: 'docker.io/library/mongo:5.0.6'
    container_name: 'mongo-db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - database-data:/data/db

volumes:
  database-data: {}