package com.cgi.space.psi.common.model;

import java.net.URI;
import java.util.Objects;
import com.cgi.space.psi.common.model.BundledProductOffering;
import com.cgi.space.psi.common.model.BundledProductOfferingOption;
import com.cgi.space.psi.common.model.ProductOfferingRef;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.net.URI;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * BundledProductOffering
 */
@com.fasterxml.jackson.annotation.JsonFilter(com.cgi.space.psi.common.config.DynamicJacksonFilterProvider.NAME)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BundledProductOffering.class, name = "BundledProductOffering")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class BundledProductOffering extends ProductOfferingRef {

  @JsonProperty("bundledProductOfferingOption")
  private BundledProductOfferingOption bundledProductOfferingOption;

  public BundledProductOffering bundledProductOfferingOption(BundledProductOfferingOption bundledProductOfferingOption) {
    this.bundledProductOfferingOption = bundledProductOfferingOption;
    return this;
  }

  /**
   * Get bundledProductOfferingOption
   * @return bundledProductOfferingOption
  */
  @Valid 
  @Schema(name = "bundledProductOfferingOption", required = false)
  public BundledProductOfferingOption getBundledProductOfferingOption() {
    return bundledProductOfferingOption;
  }

  public void setBundledProductOfferingOption(BundledProductOfferingOption bundledProductOfferingOption) {
    this.bundledProductOfferingOption = bundledProductOfferingOption;
  }

  public BundledProductOffering atType(String atType) {
    super.setAtType(atType);
    return this;
  }

  public BundledProductOffering atBaseType(String atBaseType) {
    super.setAtBaseType(atBaseType);
    return this;
  }

  public BundledProductOffering atSchemaLocation(String atSchemaLocation) {
    super.setAtSchemaLocation(atSchemaLocation);
    return this;
  }

  public BundledProductOffering href(URI href) {
    super.setHref(href);
    return this;
  }

  public BundledProductOffering id(String id) {
    super.setId(id);
    return this;
  }

  public BundledProductOffering name(String name) {
    super.setName(name);
    return this;
  }

  public BundledProductOffering atReferredType(String atReferredType) {
    super.setAtReferredType(atReferredType);
    return this;
  }

  public BundledProductOffering version(String version) {
    super.setVersion(version);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BundledProductOffering bundledProductOffering = (BundledProductOffering) o;
    return Objects.equals(this.bundledProductOfferingOption, bundledProductOffering.bundledProductOfferingOption) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundledProductOfferingOption, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BundledProductOffering {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    bundledProductOfferingOption: ").append(toIndentedString(bundledProductOfferingOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

