package com.cgi.space.psi.common.model;

import java.net.URI;
import java.util.Objects;
import com.cgi.space.psi.common.model.ConnectionSpecification;
import com.cgi.space.psi.common.model.EndpointSpecificationRef;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * ConnectionSpecification
 */
@com.fasterxml.jackson.annotation.JsonFilter(com.cgi.space.psi.common.config.DynamicJacksonFilterProvider.NAME)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ConnectionSpecification.class, name = "ConnectionSpecification")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class ConnectionSpecification {

  @JsonProperty("@type")
  private String atType;

  @JsonProperty("@baseType")
  private String atBaseType;

  @JsonProperty("@schemaLocation")
  private String atSchemaLocation;

  @JsonProperty("href")
  private URI href;

  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  /**
   * Association type.
   */
  public enum AssociationTypeEnum {
    POINTTOPOINT("pointtoPoint"),
    
    POINTTOMULTIPOINT("pointtoMultipoint");

    private String value;

    AssociationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AssociationTypeEnum fromValue(String value) {
      for (AssociationTypeEnum b : AssociationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("associationType")
  private AssociationTypeEnum associationType;

  @JsonProperty("endpointSpecification")
  @Valid
  private List<EndpointSpecificationRef> endpointSpecification = null;

  public ConnectionSpecification atType(String atType) {
    this.atType = atType;
    return this;
  }

  /**
   * When sub-classing, this defines the sub-class Extensible name
   * @return atType
  */
  @NotNull 
  @Schema(name = "@type", description = "When sub-classing, this defines the sub-class Extensible name", required = true)
  public String getAtType() {
    return atType;
  }

  public void setAtType(String atType) {
    this.atType = atType;
  }

  public ConnectionSpecification atBaseType(String atBaseType) {
    this.atBaseType = atBaseType;
    return this;
  }

  /**
   * When sub-classing, this defines the super-class
   * @return atBaseType
  */
  
  @Schema(name = "@baseType", description = "When sub-classing, this defines the super-class", required = false)
  public String getAtBaseType() {
    return atBaseType;
  }

  public void setAtBaseType(String atBaseType) {
    this.atBaseType = atBaseType;
  }

  public ConnectionSpecification atSchemaLocation(String atSchemaLocation) {
    this.atSchemaLocation = atSchemaLocation;
    return this;
  }

  /**
   * A URI to a JSON-Schema file that defines additional attributes and relationships
   * @return atSchemaLocation
  */
  
  @Schema(name = "@schemaLocation", description = "A URI to a JSON-Schema file that defines additional attributes and relationships", required = false)
  public String getAtSchemaLocation() {
    return atSchemaLocation;
  }

  public void setAtSchemaLocation(String atSchemaLocation) {
    this.atSchemaLocation = atSchemaLocation;
  }

  public ConnectionSpecification href(URI href) {
    this.href = href;
    return this;
  }

  /**
   * Hyperlink reference
   * @return href
  */
  @Valid 
  @Schema(name = "href", description = "Hyperlink reference", required = false)
  public URI getHref() {
    return href;
  }

  public void setHref(URI href) {
    this.href = href;
  }

  public ConnectionSpecification id(String id) {
    this.id = id;
    return this;
  }

  /**
   * unique identifier
   * @return id
  */
  
  @Schema(name = "id", description = "unique identifier", required = false)
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ConnectionSpecification name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Descriptive name for graph edge specification.
   * @return name
  */
  
  @Schema(name = "name", description = "Descriptive name for graph edge specification.", required = false)
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ConnectionSpecification associationType(AssociationTypeEnum associationType) {
    this.associationType = associationType;
    return this;
  }

  /**
   * Association type.
   * @return associationType
  */
  
  @Schema(name = "associationType", description = "Association type.", required = false)
  public AssociationTypeEnum getAssociationType() {
    return associationType;
  }

  public void setAssociationType(AssociationTypeEnum associationType) {
    this.associationType = associationType;
  }

  public ConnectionSpecification endpointSpecification(List<EndpointSpecificationRef> endpointSpecification) {
    this.endpointSpecification = endpointSpecification;
    return this;
  }

  public ConnectionSpecification addEndpointSpecificationItem(EndpointSpecificationRef endpointSpecificationItem) {
    if (this.endpointSpecification == null) {
      this.endpointSpecification = new ArrayList<>();
    }
    this.endpointSpecification.add(endpointSpecificationItem);
    return this;
  }

  /**
   * Specifications for resource graph vertices connected by this edge.
   * @return endpointSpecification
  */
  @Valid 
  @Schema(name = "endpointSpecification", description = "Specifications for resource graph vertices connected by this edge.", required = false)
  public List<EndpointSpecificationRef> getEndpointSpecification() {
    return endpointSpecification;
  }

  public void setEndpointSpecification(List<EndpointSpecificationRef> endpointSpecification) {
    this.endpointSpecification = endpointSpecification;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionSpecification connectionSpecification = (ConnectionSpecification) o;
    return Objects.equals(this.atType, connectionSpecification.atType) &&
        Objects.equals(this.atBaseType, connectionSpecification.atBaseType) &&
        Objects.equals(this.atSchemaLocation, connectionSpecification.atSchemaLocation) &&
        Objects.equals(this.href, connectionSpecification.href) &&
        Objects.equals(this.id, connectionSpecification.id) &&
        Objects.equals(this.name, connectionSpecification.name) &&
        Objects.equals(this.associationType, connectionSpecification.associationType) &&
        Objects.equals(this.endpointSpecification, connectionSpecification.endpointSpecification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atType, atBaseType, atSchemaLocation, href, id, name, associationType, endpointSpecification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionSpecification {\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    atBaseType: ").append(toIndentedString(atBaseType)).append("\n");
    sb.append("    atSchemaLocation: ").append(toIndentedString(atSchemaLocation)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
    sb.append("    endpointSpecification: ").append(toIndentedString(endpointSpecification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

