package com.cgi.space.psi.common.model;

import java.net.URI;
import java.util.Objects;
import com.cgi.space.psi.common.model.CharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.IntegerArrayCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.IntegerCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.MapArrayCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.MapCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.NumberArrayCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.NumberCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.ObjectArrayCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.ObjectCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.StringArrayCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.StringCharacteristicValueSpecificationMVO;
import com.cgi.space.psi.common.model.TimePeriod;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.HashMap;
import java.util.Map;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * MapCharacteristicValueSpecificationMVO
 */
@com.fasterxml.jackson.annotation.JsonFilter(com.cgi.space.psi.common.config.DynamicJacksonFilterProvider.NAME)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CharacteristicValueSpecificationMVO.class, name = "CharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = IntegerArrayCharacteristicValueSpecificationMVO.class, name = "IntegerArrayCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = IntegerCharacteristicValueSpecificationMVO.class, name = "IntegerCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = MapArrayCharacteristicValueSpecificationMVO.class, name = "MapArrayCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = MapCharacteristicValueSpecificationMVO.class, name = "MapCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = NumberArrayCharacteristicValueSpecificationMVO.class, name = "NumberArrayCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = NumberCharacteristicValueSpecificationMVO.class, name = "NumberCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = ObjectArrayCharacteristicValueSpecificationMVO.class, name = "ObjectArrayCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = ObjectCharacteristicValueSpecificationMVO.class, name = "ObjectCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = StringArrayCharacteristicValueSpecificationMVO.class, name = "StringArrayCharacteristicValueSpecification"),
  @JsonSubTypes.Type(value = StringCharacteristicValueSpecificationMVO.class, name = "StringCharacteristicValueSpecification")
})

@JsonTypeName("MapCharacteristicValueSpecification_MVO")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class MapCharacteristicValueSpecificationMVO extends CharacteristicValueSpecificationMVO {

  @JsonProperty("value")
  @Valid
  private Map<String, Object> value = null;

  public MapCharacteristicValueSpecificationMVO value(Map<String, Object> value) {
    this.value = value;
    return this;
  }

  public MapCharacteristicValueSpecificationMVO putValueItem(String key, Object valueItem) {
    if (this.value == null) {
      this.value = new HashMap<>();
    }
    this.value.put(key, valueItem);
    return this;
  }

  /**
   * Value of the characteristic
   * @return value
  */
  
  @Schema(name = "value", description = "Value of the characteristic", required = false)
  public Map<String, Object> getValue() {
    return value;
  }

  public void setValue(Map<String, Object> value) {
    this.value = value;
  }

  public MapCharacteristicValueSpecificationMVO atType(String atType) {
    super.setAtType(atType);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO atBaseType(String atBaseType) {
    super.setAtBaseType(atBaseType);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO atSchemaLocation(String atSchemaLocation) {
    super.setAtSchemaLocation(atSchemaLocation);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO valueType(String valueType) {
    super.setValueType(valueType);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO isDefault(Boolean isDefault) {
    super.setIsDefault(isDefault);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO unitOfMeasure(String unitOfMeasure) {
    super.setUnitOfMeasure(unitOfMeasure);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO validFor(TimePeriod validFor) {
    super.setValidFor(validFor);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO valueFrom(Integer valueFrom) {
    super.setValueFrom(valueFrom);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO valueTo(Integer valueTo) {
    super.setValueTo(valueTo);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO rangeInterval(String rangeInterval) {
    super.setRangeInterval(rangeInterval);
    return this;
  }

  public MapCharacteristicValueSpecificationMVO regex(String regex) {
    super.setRegex(regex);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MapCharacteristicValueSpecificationMVO mapCharacteristicValueSpecificationMVO = (MapCharacteristicValueSpecificationMVO) o;
    return Objects.equals(this.value, mapCharacteristicValueSpecificationMVO.value) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MapCharacteristicValueSpecificationMVO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

