package com.cgi.space.psi.common.model;

import java.net.URI;
import java.util.Objects;
import com.cgi.space.psi.common.model.AppointmentRefFVO;
import com.cgi.space.psi.common.model.BillingAccountRefFVO;
import com.cgi.space.psi.common.model.ItemActionType;
import com.cgi.space.psi.common.model.NoteFVO;
import com.cgi.space.psi.common.model.OrderItemRelationshipFVO;
import com.cgi.space.psi.common.model.OrderPriceFVO;
import com.cgi.space.psi.common.model.OrderTermFVO;
import com.cgi.space.psi.common.model.PaymentRefFVO;
import com.cgi.space.psi.common.model.ProductOfferingQualificationItemRefFVO;
import com.cgi.space.psi.common.model.ProductOfferingQualificationRefFVO;
import com.cgi.space.psi.common.model.ProductOfferingRefFVO;
import com.cgi.space.psi.common.model.ProductOrderItemStateType;
import com.cgi.space.psi.common.model.ProductRefOrValueFVO;
import com.cgi.space.psi.common.model.QuoteItemRefFVO;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * ProductOrderItemFVO
 */
@com.fasterxml.jackson.annotation.JsonFilter(com.cgi.space.psi.common.config.DynamicJacksonFilterProvider.NAME)

@JsonIgnoreProperties(
  value = "@type", // ignore manually set @type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the @type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ProductOrderItemFVO.class, name = "ProductOrderItem")
})

@JsonTypeName("ProductOrderItem_FVO")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class ProductOrderItemFVO {

  @JsonProperty("@type")
  private String atType;

  @JsonProperty("@baseType")
  private String atBaseType;

  @JsonProperty("@schemaLocation")
  private String atSchemaLocation;

  @JsonProperty("quantity")
  private Integer quantity;

  @JsonProperty("action")
  private ItemActionType action;

  @JsonProperty("appointment")
  private AppointmentRefFVO appointment;

  @JsonProperty("billingAccount")
  private BillingAccountRefFVO billingAccount;

  @JsonProperty("itemPrice")
  @Valid
  private List<OrderPriceFVO> itemPrice = null;

  @JsonProperty("itemTerm")
  @Valid
  private List<OrderTermFVO> itemTerm = null;

  @JsonProperty("itemTotalPrice")
  @Valid
  private List<OrderPriceFVO> itemTotalPrice = null;

  @JsonProperty("note")
  @Valid
  private List<NoteFVO> note = null;

  @JsonProperty("payment")
  @Valid
  private List<PaymentRefFVO> payment = null;

  @JsonProperty("product")
  private ProductRefOrValueFVO product;

  @JsonProperty("productOffering")
  private ProductOfferingRefFVO productOffering;

  @JsonProperty("productOfferingQualificationItem")
  private ProductOfferingQualificationItemRefFVO productOfferingQualificationItem;

  @JsonProperty("quoteItem")
  private QuoteItemRefFVO quoteItem;

  @JsonProperty("productOrderItem")
  @Valid
  private List<ProductOrderItemFVO> productOrderItem = null;

  @JsonProperty("productOrderItemRelationship")
  @Valid
  private List<OrderItemRelationshipFVO> productOrderItemRelationship = null;

  @JsonProperty("state")
  private ProductOrderItemStateType state;

  @JsonProperty("qualification")
  @Valid
  private List<ProductOfferingQualificationRefFVO> qualification = null;

  @JsonProperty("id")
  private String id;

  @JsonProperty("requestedStartDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  private OffsetDateTime requestedStartDate;

  @JsonProperty("requestedEndDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  private OffsetDateTime requestedEndDate;

  public ProductOrderItemFVO atType(String atType) {
    this.atType = atType;
    return this;
  }

  /**
   * When sub-classing, this defines the sub-class Extensible name
   * @return atType
  */
  @NotNull 
  @Schema(name = "@type", description = "When sub-classing, this defines the sub-class Extensible name", required = true)
  public String getAtType() {
    return atType;
  }

  public void setAtType(String atType) {
    this.atType = atType;
  }

  public ProductOrderItemFVO atBaseType(String atBaseType) {
    this.atBaseType = atBaseType;
    return this;
  }

  /**
   * When sub-classing, this defines the super-class
   * @return atBaseType
  */
  
  @Schema(name = "@baseType", description = "When sub-classing, this defines the super-class", required = false)
  public String getAtBaseType() {
    return atBaseType;
  }

  public void setAtBaseType(String atBaseType) {
    this.atBaseType = atBaseType;
  }

  public ProductOrderItemFVO atSchemaLocation(String atSchemaLocation) {
    this.atSchemaLocation = atSchemaLocation;
    return this;
  }

  /**
   * A URI to a JSON-Schema file that defines additional attributes and relationships
   * @return atSchemaLocation
  */
  
  @Schema(name = "@schemaLocation", description = "A URI to a JSON-Schema file that defines additional attributes and relationships", required = false)
  public String getAtSchemaLocation() {
    return atSchemaLocation;
  }

  public void setAtSchemaLocation(String atSchemaLocation) {
    this.atSchemaLocation = atSchemaLocation;
  }

  public ProductOrderItemFVO quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Quantity ordered
   * @return quantity
  */
  
  @Schema(name = "quantity", description = "Quantity ordered", required = false)
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ProductOrderItemFVO action(ItemActionType action) {
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
  */
  @NotNull @Valid 
  @Schema(name = "action", required = true)
  public ItemActionType getAction() {
    return action;
  }

  public void setAction(ItemActionType action) {
    this.action = action;
  }

  public ProductOrderItemFVO appointment(AppointmentRefFVO appointment) {
    this.appointment = appointment;
    return this;
  }

  /**
   * Get appointment
   * @return appointment
  */
  @Valid 
  @Schema(name = "appointment", required = false)
  public AppointmentRefFVO getAppointment() {
    return appointment;
  }

  public void setAppointment(AppointmentRefFVO appointment) {
    this.appointment = appointment;
  }

  public ProductOrderItemFVO billingAccount(BillingAccountRefFVO billingAccount) {
    this.billingAccount = billingAccount;
    return this;
  }

  /**
   * Get billingAccount
   * @return billingAccount
  */
  @Valid 
  @Schema(name = "billingAccount", required = false)
  public BillingAccountRefFVO getBillingAccount() {
    return billingAccount;
  }

  public void setBillingAccount(BillingAccountRefFVO billingAccount) {
    this.billingAccount = billingAccount;
  }

  public ProductOrderItemFVO itemPrice(List<OrderPriceFVO> itemPrice) {
    this.itemPrice = itemPrice;
    return this;
  }

  public ProductOrderItemFVO addItemPriceItem(OrderPriceFVO itemPriceItem) {
    if (this.itemPrice == null) {
      this.itemPrice = new ArrayList<>();
    }
    this.itemPrice.add(itemPriceItem);
    return this;
  }

  /**
   * Get itemPrice
   * @return itemPrice
  */
  @Valid 
  @Schema(name = "itemPrice", required = false)
  public List<OrderPriceFVO> getItemPrice() {
    return itemPrice;
  }

  public void setItemPrice(List<OrderPriceFVO> itemPrice) {
    this.itemPrice = itemPrice;
  }

  public ProductOrderItemFVO itemTerm(List<OrderTermFVO> itemTerm) {
    this.itemTerm = itemTerm;
    return this;
  }

  public ProductOrderItemFVO addItemTermItem(OrderTermFVO itemTermItem) {
    if (this.itemTerm == null) {
      this.itemTerm = new ArrayList<>();
    }
    this.itemTerm.add(itemTermItem);
    return this;
  }

  /**
   * Get itemTerm
   * @return itemTerm
  */
  @Valid 
  @Schema(name = "itemTerm", required = false)
  public List<OrderTermFVO> getItemTerm() {
    return itemTerm;
  }

  public void setItemTerm(List<OrderTermFVO> itemTerm) {
    this.itemTerm = itemTerm;
  }

  public ProductOrderItemFVO itemTotalPrice(List<OrderPriceFVO> itemTotalPrice) {
    this.itemTotalPrice = itemTotalPrice;
    return this;
  }

  public ProductOrderItemFVO addItemTotalPriceItem(OrderPriceFVO itemTotalPriceItem) {
    if (this.itemTotalPrice == null) {
      this.itemTotalPrice = new ArrayList<>();
    }
    this.itemTotalPrice.add(itemTotalPriceItem);
    return this;
  }

  /**
   * Get itemTotalPrice
   * @return itemTotalPrice
  */
  @Valid 
  @Schema(name = "itemTotalPrice", required = false)
  public List<OrderPriceFVO> getItemTotalPrice() {
    return itemTotalPrice;
  }

  public void setItemTotalPrice(List<OrderPriceFVO> itemTotalPrice) {
    this.itemTotalPrice = itemTotalPrice;
  }

  public ProductOrderItemFVO note(List<NoteFVO> note) {
    this.note = note;
    return this;
  }

  public ProductOrderItemFVO addNoteItem(NoteFVO noteItem) {
    if (this.note == null) {
      this.note = new ArrayList<>();
    }
    this.note.add(noteItem);
    return this;
  }

  /**
   * Get note
   * @return note
  */
  @Valid 
  @Schema(name = "note", required = false)
  public List<NoteFVO> getNote() {
    return note;
  }

  public void setNote(List<NoteFVO> note) {
    this.note = note;
  }

  public ProductOrderItemFVO payment(List<PaymentRefFVO> payment) {
    this.payment = payment;
    return this;
  }

  public ProductOrderItemFVO addPaymentItem(PaymentRefFVO paymentItem) {
    if (this.payment == null) {
      this.payment = new ArrayList<>();
    }
    this.payment.add(paymentItem);
    return this;
  }

  /**
   * Get payment
   * @return payment
  */
  @Valid 
  @Schema(name = "payment", required = false)
  public List<PaymentRefFVO> getPayment() {
    return payment;
  }

  public void setPayment(List<PaymentRefFVO> payment) {
    this.payment = payment;
  }

  public ProductOrderItemFVO product(ProductRefOrValueFVO product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
  */
  @Valid 
  @Schema(name = "product", required = false)
  public ProductRefOrValueFVO getProduct() {
    return product;
  }

  public void setProduct(ProductRefOrValueFVO product) {
    this.product = product;
  }

  public ProductOrderItemFVO productOffering(ProductOfferingRefFVO productOffering) {
    this.productOffering = productOffering;
    return this;
  }

  /**
   * Get productOffering
   * @return productOffering
  */
  @Valid 
  @Schema(name = "productOffering", required = false)
  public ProductOfferingRefFVO getProductOffering() {
    return productOffering;
  }

  public void setProductOffering(ProductOfferingRefFVO productOffering) {
    this.productOffering = productOffering;
  }

  public ProductOrderItemFVO productOfferingQualificationItem(ProductOfferingQualificationItemRefFVO productOfferingQualificationItem) {
    this.productOfferingQualificationItem = productOfferingQualificationItem;
    return this;
  }

  /**
   * Get productOfferingQualificationItem
   * @return productOfferingQualificationItem
  */
  @Valid 
  @Schema(name = "productOfferingQualificationItem", required = false)
  public ProductOfferingQualificationItemRefFVO getProductOfferingQualificationItem() {
    return productOfferingQualificationItem;
  }

  public void setProductOfferingQualificationItem(ProductOfferingQualificationItemRefFVO productOfferingQualificationItem) {
    this.productOfferingQualificationItem = productOfferingQualificationItem;
  }

  public ProductOrderItemFVO quoteItem(QuoteItemRefFVO quoteItem) {
    this.quoteItem = quoteItem;
    return this;
  }

  /**
   * Get quoteItem
   * @return quoteItem
  */
  @Valid 
  @Schema(name = "quoteItem", required = false)
  public QuoteItemRefFVO getQuoteItem() {
    return quoteItem;
  }

  public void setQuoteItem(QuoteItemRefFVO quoteItem) {
    this.quoteItem = quoteItem;
  }

  public ProductOrderItemFVO productOrderItem(List<ProductOrderItemFVO> productOrderItem) {
    this.productOrderItem = productOrderItem;
    return this;
  }

  public ProductOrderItemFVO addProductOrderItemItem(ProductOrderItemFVO productOrderItemItem) {
    if (this.productOrderItem == null) {
      this.productOrderItem = new ArrayList<>();
    }
    this.productOrderItem.add(productOrderItemItem);
    return this;
  }

  /**
   * Get productOrderItem
   * @return productOrderItem
  */
  @Valid 
  @Schema(name = "productOrderItem", required = false)
  public List<ProductOrderItemFVO> getProductOrderItem() {
    return productOrderItem;
  }

  public void setProductOrderItem(List<ProductOrderItemFVO> productOrderItem) {
    this.productOrderItem = productOrderItem;
  }

  public ProductOrderItemFVO productOrderItemRelationship(List<OrderItemRelationshipFVO> productOrderItemRelationship) {
    this.productOrderItemRelationship = productOrderItemRelationship;
    return this;
  }

  public ProductOrderItemFVO addProductOrderItemRelationshipItem(OrderItemRelationshipFVO productOrderItemRelationshipItem) {
    if (this.productOrderItemRelationship == null) {
      this.productOrderItemRelationship = new ArrayList<>();
    }
    this.productOrderItemRelationship.add(productOrderItemRelationshipItem);
    return this;
  }

  /**
   * Get productOrderItemRelationship
   * @return productOrderItemRelationship
  */
  @Valid 
  @Schema(name = "productOrderItemRelationship", required = false)
  public List<OrderItemRelationshipFVO> getProductOrderItemRelationship() {
    return productOrderItemRelationship;
  }

  public void setProductOrderItemRelationship(List<OrderItemRelationshipFVO> productOrderItemRelationship) {
    this.productOrderItemRelationship = productOrderItemRelationship;
  }

  public ProductOrderItemFVO state(ProductOrderItemStateType state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
  */
  @Valid 
  @Schema(name = "state", required = false)
  public ProductOrderItemStateType getState() {
    return state;
  }

  public void setState(ProductOrderItemStateType state) {
    this.state = state;
  }

  public ProductOrderItemFVO qualification(List<ProductOfferingQualificationRefFVO> qualification) {
    this.qualification = qualification;
    return this;
  }

  public ProductOrderItemFVO addQualificationItem(ProductOfferingQualificationRefFVO qualificationItem) {
    if (this.qualification == null) {
      this.qualification = new ArrayList<>();
    }
    this.qualification.add(qualificationItem);
    return this;
  }

  /**
   * Get qualification
   * @return qualification
  */
  @Valid 
  @Schema(name = "qualification", required = false)
  public List<ProductOfferingQualificationRefFVO> getQualification() {
    return qualification;
  }

  public void setQualification(List<ProductOfferingQualificationRefFVO> qualification) {
    this.qualification = qualification;
  }

  public ProductOrderItemFVO id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Identifier of the ProductOrder item (generally it is a sequence number 01, 02, 03, ...)
   * @return id
  */
  @NotNull 
  @Schema(name = "id", description = "Identifier of the ProductOrder item (generally it is a sequence number 01, 02, 03, ...)", required = true)
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProductOrderItemFVO requestedStartDate(OffsetDateTime requestedStartDate) {
    this.requestedStartDate = requestedStartDate;
    return this;
  }

  /**
   * Order fulfillment start date wished by the requestor. This is used when, for any reason, the requestor cannot allow the seller to operationally begin the fulfillment before a date. 
   * @return requestedStartDate
  */
  @Valid 
  @Schema(name = "requestedStartDate", description = "Order fulfillment start date wished by the requestor. This is used when, for any reason, the requestor cannot allow the seller to operationally begin the fulfillment before a date. ", required = false)
  public OffsetDateTime getRequestedStartDate() {
    return requestedStartDate;
  }

  public void setRequestedStartDate(OffsetDateTime requestedStartDate) {
    this.requestedStartDate = requestedStartDate;
  }

  public ProductOrderItemFVO requestedEndDate(OffsetDateTime requestedEndDate) {
    this.requestedEndDate = requestedEndDate;
    return this;
  }

  /**
   * Order fulfillment end date wished by the requestor. This is used when, for any reason, the requestor cannot allow the seller to operationally shutdown before a date.
   * @return requestedEndDate
  */
  @Valid 
  @Schema(name = "requestedEndDate", description = "Order fulfillment end date wished by the requestor. This is used when, for any reason, the requestor cannot allow the seller to operationally shutdown before a date.", required = false)
  public OffsetDateTime getRequestedEndDate() {
    return requestedEndDate;
  }

  public void setRequestedEndDate(OffsetDateTime requestedEndDate) {
    this.requestedEndDate = requestedEndDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductOrderItemFVO productOrderItemFVO = (ProductOrderItemFVO) o;
    return Objects.equals(this.atType, productOrderItemFVO.atType) &&
        Objects.equals(this.atBaseType, productOrderItemFVO.atBaseType) &&
        Objects.equals(this.atSchemaLocation, productOrderItemFVO.atSchemaLocation) &&
        Objects.equals(this.quantity, productOrderItemFVO.quantity) &&
        Objects.equals(this.action, productOrderItemFVO.action) &&
        Objects.equals(this.appointment, productOrderItemFVO.appointment) &&
        Objects.equals(this.billingAccount, productOrderItemFVO.billingAccount) &&
        Objects.equals(this.itemPrice, productOrderItemFVO.itemPrice) &&
        Objects.equals(this.itemTerm, productOrderItemFVO.itemTerm) &&
        Objects.equals(this.itemTotalPrice, productOrderItemFVO.itemTotalPrice) &&
        Objects.equals(this.note, productOrderItemFVO.note) &&
        Objects.equals(this.payment, productOrderItemFVO.payment) &&
        Objects.equals(this.product, productOrderItemFVO.product) &&
        Objects.equals(this.productOffering, productOrderItemFVO.productOffering) &&
        Objects.equals(this.productOfferingQualificationItem, productOrderItemFVO.productOfferingQualificationItem) &&
        Objects.equals(this.quoteItem, productOrderItemFVO.quoteItem) &&
        Objects.equals(this.productOrderItem, productOrderItemFVO.productOrderItem) &&
        Objects.equals(this.productOrderItemRelationship, productOrderItemFVO.productOrderItemRelationship) &&
        Objects.equals(this.state, productOrderItemFVO.state) &&
        Objects.equals(this.qualification, productOrderItemFVO.qualification) &&
        Objects.equals(this.id, productOrderItemFVO.id) &&
        Objects.equals(this.requestedStartDate, productOrderItemFVO.requestedStartDate) &&
        Objects.equals(this.requestedEndDate, productOrderItemFVO.requestedEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atType, atBaseType, atSchemaLocation, quantity, action, appointment, billingAccount, itemPrice, itemTerm, itemTotalPrice, note, payment, product, productOffering, productOfferingQualificationItem, quoteItem, productOrderItem, productOrderItemRelationship, state, qualification, id, requestedStartDate, requestedEndDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductOrderItemFVO {\n");
    sb.append("    atType: ").append(toIndentedString(atType)).append("\n");
    sb.append("    atBaseType: ").append(toIndentedString(atBaseType)).append("\n");
    sb.append("    atSchemaLocation: ").append(toIndentedString(atSchemaLocation)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    appointment: ").append(toIndentedString(appointment)).append("\n");
    sb.append("    billingAccount: ").append(toIndentedString(billingAccount)).append("\n");
    sb.append("    itemPrice: ").append(toIndentedString(itemPrice)).append("\n");
    sb.append("    itemTerm: ").append(toIndentedString(itemTerm)).append("\n");
    sb.append("    itemTotalPrice: ").append(toIndentedString(itemTotalPrice)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    productOffering: ").append(toIndentedString(productOffering)).append("\n");
    sb.append("    productOfferingQualificationItem: ").append(toIndentedString(productOfferingQualificationItem)).append("\n");
    sb.append("    quoteItem: ").append(toIndentedString(quoteItem)).append("\n");
    sb.append("    productOrderItem: ").append(toIndentedString(productOrderItem)).append("\n");
    sb.append("    productOrderItemRelationship: ").append(toIndentedString(productOrderItemRelationship)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    qualification: ").append(toIndentedString(qualification)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    requestedStartDate: ").append(toIndentedString(requestedStartDate)).append("\n");
    sb.append("    requestedEndDate: ").append(toIndentedString(requestedEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

