version: '3.8'

services:

  frontend:
    image: mission-management-frontend:latest
    build: .
    container_name: mission-frontend
    env_file:
      - "./.env"
    # environment:
    #   PUBLIC_BASE_URL: "http://localhost:3000"
    #   PUBLIC_MISSION_MANAGEMENT_URL: "http://<your ip>:7000/mission"
    #   PUBLIC_MISSIONTEMPLATE_MANAGEMENT_URL: "http://<your ip>:7001/missionTemplate"
    #   PUBLIC_PARTY_MANAGEMENT_URL: "http://localhost:3000/api/organization"
    #   PUBLIC_TEAM_URL: "http://localhost:3000/api/teams"
    #   PUBLIC_SERVICETEMPLATE_URL: "http://localhost:3000/api/serviceTemplates"

    ports:
      - 3000:3000
    volumes:
      - /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/ssl/certs/cert.pem:ro
