apiVersion: v1
kind: Service
metadata:
  name: {{ include "mission-management-frontend.fullname" . }}
  labels:
    {{- include "mission-management-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mission-management-frontend.selectorLabels" . | nindent 4 }}
