/*
Mission Management

## PSID API Reference: PSID002 - Mission Management  The Mission API enables customers to create, update and delete missions. A mission is composed of one or more teams, their areas of operation and communication needs. The data can be used to issue an inquiry for matching products (see PSID001).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MissionUpdate A mission of a customer. Skipped properties: id,href,lastUpdated
type MissionUpdate struct {
	// Name of the mission
	Name *string `json:"name,omitempty"`
	// Description of the mission
	Description *string `json:"description,omitempty"`
	// Category of the mission like 'Humanitarian Aid', 'Wildfire Fighting' and so on.
	Category *string `json:"category,omitempty"`
	Timeframe *TimePeriod `json:"timeframe,omitempty"`
	Status *MissionStatusType `json:"status,omitempty"`
	Characteristic []Characteristic `json:"characteristic,omitempty"`
	// List of places where the mission is conducted.
	Place []PlaceRefOrValue `json:"place,omitempty"`
	// List of assets for this mission.
	Asset []MissionAsset `json:"asset,omitempty"`
	// Relation to other missions.
	MissionRelationship []MissionRelationship `json:"missionRelationship,omitempty"`
	// A related party defines party or party role linked to a specific entity.
	RelatedParty []RelatedParty `json:"relatedParty,omitempty"`
	// When sub-classing, this defines the super-class.
	BaseType *string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation *string `json:"@schemaLocation,omitempty"`
	// When sub-classing, this defines the sub-class entity name.
	Type *string `json:"@type,omitempty"`
}

// NewMissionUpdate instantiates a new MissionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMissionUpdate() *MissionUpdate {
	this := MissionUpdate{}
	return &this
}

// NewMissionUpdateWithDefaults instantiates a new MissionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMissionUpdateWithDefaults() *MissionUpdate {
	this := MissionUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MissionUpdate) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MissionUpdate) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MissionUpdate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MissionUpdate) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MissionUpdate) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MissionUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *MissionUpdate) GetCategory() string {
	if o == nil || isNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetCategoryOk() (*string, bool) {
	if o == nil || isNil(o.Category) {
    return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *MissionUpdate) HasCategory() bool {
	if o != nil && !isNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *MissionUpdate) SetCategory(v string) {
	o.Category = &v
}

// GetTimeframe returns the Timeframe field value if set, zero value otherwise.
func (o *MissionUpdate) GetTimeframe() TimePeriod {
	if o == nil || isNil(o.Timeframe) {
		var ret TimePeriod
		return ret
	}
	return *o.Timeframe
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetTimeframeOk() (*TimePeriod, bool) {
	if o == nil || isNil(o.Timeframe) {
    return nil, false
	}
	return o.Timeframe, true
}

// HasTimeframe returns a boolean if a field has been set.
func (o *MissionUpdate) HasTimeframe() bool {
	if o != nil && !isNil(o.Timeframe) {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given TimePeriod and assigns it to the Timeframe field.
func (o *MissionUpdate) SetTimeframe(v TimePeriod) {
	o.Timeframe = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MissionUpdate) GetStatus() MissionStatusType {
	if o == nil || isNil(o.Status) {
		var ret MissionStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetStatusOk() (*MissionStatusType, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MissionUpdate) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given MissionStatusType and assigns it to the Status field.
func (o *MissionUpdate) SetStatus(v MissionStatusType) {
	o.Status = &v
}

// GetCharacteristic returns the Characteristic field value if set, zero value otherwise.
func (o *MissionUpdate) GetCharacteristic() []Characteristic {
	if o == nil || isNil(o.Characteristic) {
		var ret []Characteristic
		return ret
	}
	return o.Characteristic
}

// GetCharacteristicOk returns a tuple with the Characteristic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetCharacteristicOk() ([]Characteristic, bool) {
	if o == nil || isNil(o.Characteristic) {
    return nil, false
	}
	return o.Characteristic, true
}

// HasCharacteristic returns a boolean if a field has been set.
func (o *MissionUpdate) HasCharacteristic() bool {
	if o != nil && !isNil(o.Characteristic) {
		return true
	}

	return false
}

// SetCharacteristic gets a reference to the given []Characteristic and assigns it to the Characteristic field.
func (o *MissionUpdate) SetCharacteristic(v []Characteristic) {
	o.Characteristic = v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *MissionUpdate) GetPlace() []PlaceRefOrValue {
	if o == nil || isNil(o.Place) {
		var ret []PlaceRefOrValue
		return ret
	}
	return o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetPlaceOk() ([]PlaceRefOrValue, bool) {
	if o == nil || isNil(o.Place) {
    return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *MissionUpdate) HasPlace() bool {
	if o != nil && !isNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given []PlaceRefOrValue and assigns it to the Place field.
func (o *MissionUpdate) SetPlace(v []PlaceRefOrValue) {
	o.Place = v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *MissionUpdate) GetAsset() []MissionAsset {
	if o == nil || isNil(o.Asset) {
		var ret []MissionAsset
		return ret
	}
	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetAssetOk() ([]MissionAsset, bool) {
	if o == nil || isNil(o.Asset) {
    return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *MissionUpdate) HasAsset() bool {
	if o != nil && !isNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given []MissionAsset and assigns it to the Asset field.
func (o *MissionUpdate) SetAsset(v []MissionAsset) {
	o.Asset = v
}

// GetMissionRelationship returns the MissionRelationship field value if set, zero value otherwise.
func (o *MissionUpdate) GetMissionRelationship() []MissionRelationship {
	if o == nil || isNil(o.MissionRelationship) {
		var ret []MissionRelationship
		return ret
	}
	return o.MissionRelationship
}

// GetMissionRelationshipOk returns a tuple with the MissionRelationship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetMissionRelationshipOk() ([]MissionRelationship, bool) {
	if o == nil || isNil(o.MissionRelationship) {
    return nil, false
	}
	return o.MissionRelationship, true
}

// HasMissionRelationship returns a boolean if a field has been set.
func (o *MissionUpdate) HasMissionRelationship() bool {
	if o != nil && !isNil(o.MissionRelationship) {
		return true
	}

	return false
}

// SetMissionRelationship gets a reference to the given []MissionRelationship and assigns it to the MissionRelationship field.
func (o *MissionUpdate) SetMissionRelationship(v []MissionRelationship) {
	o.MissionRelationship = v
}

// GetRelatedParty returns the RelatedParty field value if set, zero value otherwise.
func (o *MissionUpdate) GetRelatedParty() []RelatedParty {
	if o == nil || isNil(o.RelatedParty) {
		var ret []RelatedParty
		return ret
	}
	return o.RelatedParty
}

// GetRelatedPartyOk returns a tuple with the RelatedParty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetRelatedPartyOk() ([]RelatedParty, bool) {
	if o == nil || isNil(o.RelatedParty) {
    return nil, false
	}
	return o.RelatedParty, true
}

// HasRelatedParty returns a boolean if a field has been set.
func (o *MissionUpdate) HasRelatedParty() bool {
	if o != nil && !isNil(o.RelatedParty) {
		return true
	}

	return false
}

// SetRelatedParty gets a reference to the given []RelatedParty and assigns it to the RelatedParty field.
func (o *MissionUpdate) SetRelatedParty(v []RelatedParty) {
	o.RelatedParty = v
}

// GetBaseType returns the BaseType field value if set, zero value otherwise.
func (o *MissionUpdate) GetBaseType() string {
	if o == nil || isNil(o.BaseType) {
		var ret string
		return ret
	}
	return *o.BaseType
}

// GetBaseTypeOk returns a tuple with the BaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetBaseTypeOk() (*string, bool) {
	if o == nil || isNil(o.BaseType) {
    return nil, false
	}
	return o.BaseType, true
}

// HasBaseType returns a boolean if a field has been set.
func (o *MissionUpdate) HasBaseType() bool {
	if o != nil && !isNil(o.BaseType) {
		return true
	}

	return false
}

// SetBaseType gets a reference to the given string and assigns it to the BaseType field.
func (o *MissionUpdate) SetBaseType(v string) {
	o.BaseType = &v
}

// GetSchemaLocation returns the SchemaLocation field value if set, zero value otherwise.
func (o *MissionUpdate) GetSchemaLocation() string {
	if o == nil || isNil(o.SchemaLocation) {
		var ret string
		return ret
	}
	return *o.SchemaLocation
}

// GetSchemaLocationOk returns a tuple with the SchemaLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetSchemaLocationOk() (*string, bool) {
	if o == nil || isNil(o.SchemaLocation) {
    return nil, false
	}
	return o.SchemaLocation, true
}

// HasSchemaLocation returns a boolean if a field has been set.
func (o *MissionUpdate) HasSchemaLocation() bool {
	if o != nil && !isNil(o.SchemaLocation) {
		return true
	}

	return false
}

// SetSchemaLocation gets a reference to the given string and assigns it to the SchemaLocation field.
func (o *MissionUpdate) SetSchemaLocation(v string) {
	o.SchemaLocation = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MissionUpdate) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MissionUpdate) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MissionUpdate) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MissionUpdate) SetType(v string) {
	o.Type = &v
}

func (o MissionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !isNil(o.Timeframe) {
		toSerialize["timeframe"] = o.Timeframe
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !isNil(o.Characteristic) {
		toSerialize["characteristic"] = o.Characteristic
	}
	if !isNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !isNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !isNil(o.MissionRelationship) {
		toSerialize["missionRelationship"] = o.MissionRelationship
	}
	if !isNil(o.RelatedParty) {
		toSerialize["relatedParty"] = o.RelatedParty
	}
	if !isNil(o.BaseType) {
		toSerialize["@baseType"] = o.BaseType
	}
	if !isNil(o.SchemaLocation) {
		toSerialize["@schemaLocation"] = o.SchemaLocation
	}
	if !isNil(o.Type) {
		toSerialize["@type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableMissionUpdate struct {
	value *MissionUpdate
	isSet bool
}

func (v NullableMissionUpdate) Get() *MissionUpdate {
	return v.value
}

func (v *NullableMissionUpdate) Set(val *MissionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableMissionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableMissionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMissionUpdate(val *MissionUpdate) *NullableMissionUpdate {
	return &NullableMissionUpdate{value: val, isSet: true}
}

func (v NullableMissionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMissionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


